import type { Signal } from './types'

const NOW = new Date().toISOString()
const AGO = (h: number) => new Date(Date.now() - h * 3_600_000).toISOString()

export const DEMO_SIGNALS: Signal[] = [
  {
    id: 'demo-1',
    created_by: 'demo',
    pair: 'XAUUSD',
    direction: 'buy',
    timeframe: 'H4',
    session: 'london',
    entry_zone_low: 3312.00,
    entry_zone_high: 3315.00,
    stop_loss: 3302.00,
    take_profit_1: 3332.00,
    take_profit_2: 3352.00,
    take_profit_3: 3375.00,
    risk_reward_1: 2.0,
    risk_reward_2: 4.0,
    risk_reward_3: 6.3,
    pip_risk: 100,
    smc_patterns: ['OB', 'BOS', 'FVG'],
    bias: 'bullish',
    htf_bias: 'bullish',
    confluence_score: 8,
    status: 'active',
    tier_required: 'free',
    result_pips: null,
    closed_price: null,
    analysis_text: 'Price tapped into H4 Demand OB after BOS on H1. FVG aligned with 0.62 fib. Strong bullish confluence.',
    chart_url: null,
    notes: null,
    telegram_message_id: null,
    published_at: AGO(2),
    invalidated_at: null,
    closed_at: null,
    created_at: AGO(2),
    updated_at: AGO(2),
  },
  {
    id: 'demo-2',
    created_by: 'demo',
    pair: 'EURUSD',
    direction: 'sell',
    timeframe: 'H1',
    session: 'london',
    entry_zone_low: 1.1095,
    entry_zone_high: 1.1100,
    stop_loss: 1.1128,
    take_profit_1: 1.1065,
    take_profit_2: 1.1035,
    take_profit_3: null,
    risk_reward_1: 1.1,
    risk_reward_2: 2.0,
    risk_reward_3: null,
    pip_risk: 33,
    smc_patterns: ['CHOCH', 'LIQUIDITY_SWEEP', 'PREMIUM_OB'],
    bias: 'bearish',
    htf_bias: 'bearish',
    confluence_score: 9,
    status: 'tp1_hit',
    tier_required: 'free',
    result_pips: 31.5,
    closed_price: 1.1065,
    analysis_text: 'CHOCH on M15 confirmed bearish bias. Swept buy-side liquidity at 1.1100 premium OB.',
    chart_url: null,
    notes: null,
    telegram_message_id: null,
    published_at: AGO(6),
    invalidated_at: null,
    closed_at: AGO(3),
    created_at: AGO(7),
    updated_at: AGO(3),
  },
  {
    id: 'demo-3',
    created_by: 'demo',
    pair: 'GBPUSD',
    direction: 'buy',
    timeframe: 'M15',
    session: 'london_newyork_overlap',
    entry_zone_low: 1.2720,
    entry_zone_high: 1.2728,
    stop_loss: 1.2694,
    take_profit_1: 1.2774,
    take_profit_2: 1.2810,
    take_profit_3: null,
    risk_reward_1: 2.1,
    risk_reward_2: 4.2,
    risk_reward_3: null,
    pip_risk: 26,
    smc_patterns: ['BREAKER', 'OB', 'INDUCEMENT'],
    bias: 'bullish',
    htf_bias: 'bullish',
    confluence_score: 7,
    status: 'active',
    tier_required: 'free',
    result_pips: null,
    closed_price: null,
    analysis_text: 'Breaker block from prior BOS zone. Inducement swept below M15 lows. Entry on retest.',
    chart_url: null,
    notes: null,
    telegram_message_id: null,
    published_at: AGO(1),
    invalidated_at: null,
    closed_at: null,
    created_at: AGO(1),
    updated_at: AGO(1),
  },
  {
    id: 'demo-4',
    created_by: 'demo',
    pair: 'USDJPY',
    direction: 'buy',
    timeframe: 'H4',
    session: 'newyork',
    entry_zone_low: 149.20,
    entry_zone_high: 149.45,
    stop_loss: 148.78,
    take_profit_1: 150.25,
    take_profit_2: 151.00,
    take_profit_3: null,
    risk_reward_1: 2.5,
    risk_reward_2: 4.3,
    risk_reward_3: null,
    pip_risk: 42,
    smc_patterns: ['MSS', 'PREMIUM_OB', 'INDUCEMENT'],
    bias: 'bullish',
    htf_bias: 'bullish',
    confluence_score: 9,
    status: 'pending',
    tier_required: 'elite',
    result_pips: null,
    closed_price: null,
    analysis_text: 'H4 MSS confirmed. Premium OB with 4H+ FVG confluence. Waiting for NY open to trigger.',
    chart_url: null,
    notes: null,
    telegram_message_id: null,
    published_at: AGO(0.5),
    invalidated_at: null,
    closed_at: null,
    created_at: AGO(0.5),
    updated_at: AGO(0.5),
  },
  {
    id: 'demo-5',
    created_by: 'demo',
    pair: 'XAUUSD',
    direction: 'sell',
    timeframe: 'H1',
    session: 'london',
    entry_zone_low: 3338.00,
    entry_zone_high: 3342.00,
    stop_loss: 3352.00,
    take_profit_1: 3325.00,
    take_profit_2: 3310.00,
    take_profit_3: null,
    risk_reward_1: 1.3,
    risk_reward_2: 2.8,
    risk_reward_3: null,
    pip_risk: 140,
    smc_patterns: ['CHOCH', 'OB', 'FVG', 'MITIGATION'],
    bias: 'bearish',
    htf_bias: 'bearish',
    confluence_score: 8,
    status: 'tp2_hit',
    tier_required: 'pro',
    result_pips: 142.5,
    closed_price: 3310.00,
    analysis_text: 'Daily CHOCH confirmed bearish. H1 OB mitigation complete. FVG filled. Both TPs hit.',
    chart_url: null,
    notes: null,
    telegram_message_id: null,
    published_at: AGO(24),
    invalidated_at: null,
    closed_at: AGO(12),
    created_at: AGO(25),
    updated_at: AGO(12),
  },
  {
    id: 'demo-6',
    created_by: 'demo',
    pair: 'GBPJPY',
    direction: 'sell',
    timeframe: 'H1',
    session: 'london',
    entry_zone_low: 191.50,
    entry_zone_high: 191.85,
    stop_loss: 192.25,
    take_profit_1: 190.70,
    take_profit_2: null,
    take_profit_3: null,
    risk_reward_1: 2.0,
    risk_reward_2: null,
    risk_reward_3: null,
    pip_risk: 40,
    smc_patterns: ['BOS', 'POI', 'LIQUIDITY_SWEEP'],
    bias: 'bearish',
    htf_bias: 'neutral',
    confluence_score: 6,
    status: 'sl_hit',
    tier_required: 'free',
    result_pips: -38.0,
    closed_price: 192.22,
    analysis_text: 'BOS setup invalidated by unexpected bullish news spike. SL triggered.',
    chart_url: null,
    notes: null,
    telegram_message_id: null,
    published_at: AGO(48),
    invalidated_at: null,
    closed_at: AGO(44),
    created_at: AGO(49),
    updated_at: AGO(44),
  },
]

export const DEMO_STATS = {
  avg_win_rate: 68.5,
  total_trades: 47,
  avg_profit_factor: 1.84,
  total_pips_30d: 312.5,
}

export const DEMO_PERF = [
  { pair: 'XAUUSD', total_signals: 18, win_rate_pct: 72.2 },
  { pair: 'EURUSD', total_signals: 14, win_rate_pct: 71.4 },
  { pair: 'GBPUSD', total_signals: 11, win_rate_pct: 63.6 },
  { pair: 'USDJPY', total_signals:  9, win_rate_pct: 66.7 },
  { pair: 'GBPJPY', total_signals:  7, win_rate_pct: 57.1 },
]
